### ISSUE TITLE
why is not BTCUSDTM  found in getlist methof of contract? 

### ISSUE THREAD

**Issue by myehrajat** [Kucoin/kucoin-futures-php-sdk#11]
this is the respone of my code

    $contract = new Contract();
    try {
    $results = $contract->getList();
    // = $contract->getDetail("BTCUSDTM");
    //echo '<pre>';
    //foreach($results as $result ){
      //  echo $result['symbol']."<br>";
    //}
    var_dump($result);
    //echo '</pre>';

} catch (HttpException $e) {
    var_dump($e->getMessage());
} catch (BusinessException $e) {
    var_dump($e->getMessage());
}

array(127) { [0]=> array(55) { ["symbol"]=> string(8) "XBTUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1585555200000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "XBT" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(1) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(0.001) ["initialMargin"]=> float(0.01) ["maintainMargin"]=> float(0.005) ["maxRiskLimit"]=> int(2000000) ["minRiskLimit"]=> int(2000000) ["riskStep"]=> int(1000000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".XBTINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".XBTUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KXBTUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(9.0E-5) ["predictedFundingFeeRate"]=> float(-4.1E-5) ["openInterest"]=> string(8) "17909853" ["turnoverOf24h"]=> float(2202480093.7109) ["volumeOf24h"]=> float(97469.685) ["markPrice"]=> float(23136.94) ["indexPrice"]=> float(23135.66) ["lastTradePrice"]=> float(23125) ["nextFundingRateTime"]=> int(17674538) ["maxLeverage"]=> int(100) ["sourceExchanges"]=> array(6) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" [5]=> string(6) "Hitbtc" } ["premiumsSymbol1M"]=> string(11) ".XBTUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".XBTUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".XBTINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> int(21411) ["highPrice"]=> int(23465) ["priceChgPct"]=> float(0.0779) ["priceChg"]=> int(1672) } [1]=> array(55) { ["symbol"]=> string(7) "XBTUSDM" ["rootSymbol"]=> string(3) "XBT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1552638575000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "XBT" ["quoteCurrency"]=> string(3) "USD" ["settleCurrency"]=> string(3) "XBT" ["maxOrderQty"]=> int(10000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(1) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(-1) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(40) ["minRiskLimit"]=> int(40) ["riskStep"]=> int(20) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(false) ["isInverse"]=> bool(true) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".XBTINT8H" ["fundingQuoteSymbol"]=> string(9) ".USDINT8H" ["fundingRateSymbol"]=> string(13) ".XBTUSDMFPI8H" ["indexSymbol"]=> string(5) ".BXBT" ["settlementSymbol"]=> NULL ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(8) "40355446" ["turnoverOf24h"]=> float(955.36593352) ["volumeOf24h"]=> float(21532516) ["markPrice"]=> float(23151.87) ["indexPrice"]=> float(23148.73) ["lastTradePrice"]=> float(23143) ["nextFundingRateTime"]=> int(17666396) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(6) { [0]=> string(8) "Bitstamp" [1]=> string(7) "Bittrex" [2]=> string(8) "Coinbase" [3]=> string(6) "Gemini" [4]=> string(6) "Kraken" [5]=> string(6) "Liquid" } ["premiumsSymbol1M"]=> string(10) ".XBTUSDMPI" ["premiumsSymbol8H"]=> string(12) ".XBTUSDMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".XBTINT" ["fundingQuoteSymbol1M"]=> string(7) ".USDINT" ["lowPrice"]=> int(21425) ["highPrice"]=> int(23514) ["priceChgPct"]=> float(0.0775) ["priceChg"]=> int(1664) } [2]=> array(55) { ["symbol"]=> string(8) "ETHUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1591086000000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "ETH" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.05) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(0.01) ["initialMargin"]=> float(0.01) ["maintainMargin"]=> float(0.005) ["maxRiskLimit"]=> int(1000000) ["minRiskLimit"]=> int(1000000) ["riskStep"]=> int(500000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".ETHINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".ETHUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KETHUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(4.6E-5) ["predictedFundingFeeRate"]=> float(6.6E-5) ["openInterest"]=> string(8) "16544940" ["turnoverOf24h"]=> float(2204935248.1904) ["volumeOf24h"]=> float(1380518.54) ["markPrice"]=> float(1649.88) ["indexPrice"]=> float(1649.83) ["lastTradePrice"]=> float(1649.6) ["nextFundingRateTime"]=> int(17666388) ["maxLeverage"]=> int(100) ["sourceExchanges"]=> array(6) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" [5]=> string(6) "Hitbtc" } ["premiumsSymbol1M"]=> string(11) ".ETHUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".ETHUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".ETHINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(1475.2) ["highPrice"]=> float(1679) ["priceChgPct"]=> float(0.105) ["priceChg"]=> float(156.6) } [3]=> array(55) { ["symbol"]=> string(8) "BCHUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1595406600000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "BCH" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.05) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(0.01) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(500000) ["minRiskLimit"]=> int(500000) ["riskStep"]=> int(200000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".BCHINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".BCHUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KBCHUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(7) "9105884" ["turnoverOf24h"]=> float(15365692.615529) ["volumeOf24h"]=> float(112644.87) ["markPrice"]=> float(145.6) ["indexPrice"]=> float(145.59) ["lastTradePrice"]=> float(145.6) ["nextFundingRateTime"]=> int(17666380) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(6) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" [5]=> string(6) "Hitbtc" } ["premiumsSymbol1M"]=> string(11) ".BCHUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".BCHUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".BCHINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(117.1) ["highPrice"]=> float(148.25) ["priceChgPct"]=> float(0.2258) ["priceChg"]=> float(26.8) } [4]=> array(55) { ["symbol"]=> string(8) "BSVUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1595406600000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "BSV" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.05) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(0.01) ["initialMargin"]=> float(0.05) ["maintainMargin"]=> float(0.025) ["maxRiskLimit"]=> int(200000) ["minRiskLimit"]=> int(200000) ["riskStep"]=> int(100000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".BSVINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".BSVUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KBSVUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(7) "4723574" ["turnoverOf24h"]=> float(446478.30828934) ["volumeOf24h"]=> float(7480.11) ["markPrice"]=> float(60.83) ["indexPrice"]=> float(60.83) ["lastTradePrice"]=> float(60.7) ["nextFundingRateTime"]=> int(17660983) ["maxLeverage"]=> int(20) ["sourceExchanges"]=> array(5) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(6) "Kucoin" [3]=> string(8) "Poloniex" [4]=> string(6) "Hitbtc" } ["premiumsSymbol1M"]=> string(11) ".BSVUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".BSVUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".BSVINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(54.35) ["highPrice"]=> float(63.25) ["priceChgPct"]=> float(0.1076) ["priceChg"]=> float(5.9) } [5]=> array(55) { ["symbol"]=> string(9) "LINKUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1600934400000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(4) "LINK" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.001) ["indexPriceTickSize"]=> float(0.001) ["multiplier"]=> float(0.1) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(500000) ["minRiskLimit"]=> int(500000) ["riskStep"]=> int(200000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(10) ".LINKINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(15) ".LINKUSDTMFPI8H" ["indexSymbol"]=> string(10) ".KLINKUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(8) "19833983" ["turnoverOf24h"]=> float(19466733.010279) ["volumeOf24h"]=> float(2894947.5) ["markPrice"]=> float(6.859) ["indexPrice"]=> float(6.859) ["lastTradePrice"]=> float(6.857) ["nextFundingRateTime"]=> int(17666375) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(6) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" [5]=> string(6) "Hitbtc" } ["premiumsSymbol1M"]=> string(12) ".LINKUSDTMPI" ["premiumsSymbol8H"]=> string(14) ".LINKUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(8) ".LINKINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(6.263) ["highPrice"]=> float(6.968) ["priceChgPct"]=> float(0.0803) ["priceChg"]=> float(0.51) } [6]=> array(55) { ["symbol"]=> string(8) "UNIUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1601280000000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "UNI" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.001) ["indexPriceTickSize"]=> float(0.001) ["multiplier"]=> float(1) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(500000) ["minRiskLimit"]=> int(500000) ["riskStep"]=> int(200000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".UNIINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".UNIUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KUNIUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(8.8E-5) ["predictedFundingFeeRate"]=> float(-0.000175) ["openInterest"]=> string(7) "1428633" ["turnoverOf24h"]=> float(54092427.637068) ["volumeOf24h"]=> float(6740510) ["markPrice"]=> float(8.694) ["indexPrice"]=> float(8.694) ["lastTradePrice"]=> float(8.68) ["nextFundingRateTime"]=> int(17666370) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(5) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" } ["premiumsSymbol1M"]=> string(11) ".UNIUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".UNIUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".UNIINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(6.751) ["highPrice"]=> float(8.729) ["priceChgPct"]=> float(0.2779) ["priceChg"]=> float(1.887) } [7]=> array(55) { ["symbol"]=> string(8) "YFIUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1601280000000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "YFI" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(1) ["indexPriceTickSize"]=> float(0.1) ["multiplier"]=> float(0.0001) ["initialMargin"]=> float(0.05) ["maintainMargin"]=> float(0.025) ["maxRiskLimit"]=> int(200000) ["minRiskLimit"]=> int(200000) ["riskStep"]=> int(100000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".YFIINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".YFIUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KYFIUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(7) "5758279" ["turnoverOf24h"]=> float(2731697.4275577) ["volumeOf24h"]=> float(379.0153) ["markPrice"]=> float(7423.5) ["indexPrice"]=> float(7423) ["lastTradePrice"]=> float(7417) ["nextFundingRateTime"]=> int(17660976) ["maxLeverage"]=> int(20) ["sourceExchanges"]=> array(5) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" } ["premiumsSymbol1M"]=> string(11) ".YFIUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".YFIUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".YFIINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> int(6637) ["highPrice"]=> int(7573) ["priceChgPct"]=> float(0.1003) ["priceChg"]=> int(676) } [8]=> array(55) { ["symbol"]=> string(8) "EOSUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1602501300000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "EOS" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.001) ["indexPriceTickSize"]=> float(0.001) ["multiplier"]=> float(1) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(500000) ["minRiskLimit"]=> int(500000) ["riskStep"]=> int(200000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".EOSINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".EOSUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KEOSUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(0.0001) ["predictedFundingFeeRate"]=> float(0.0001) ["openInterest"]=> string(8) "10054262" ["turnoverOf24h"]=> float(6401617.5364499) ["volumeOf24h"]=> float(5175337) ["markPrice"]=> float(1.277) ["indexPrice"]=> float(1.277) ["lastTradePrice"]=> float(1.276) ["nextFundingRateTime"]=> int(17666363) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(5) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(8) "Poloniex" } ["premiumsSymbol1M"]=> string(11) ".EOSUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".EOSUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".EOSINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(1.122) ["highPrice"]=> float(1.301) ["priceChgPct"]=> float(0.1302) ["priceChg"]=> float(0.147) } [9]=> array(55) { ["symbol"]=> string(8) "DOTUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1602501300000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "DOT" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.001) ["indexPriceTickSize"]=> float(0.001) ["multiplier"]=> float(1) ["initialMargin"]=> float(0.02) ["maintainMargin"]=> float(0.01) ["maxRiskLimit"]=> int(200000) ["minRiskLimit"]=> int(200000) ["riskStep"]=> int(100000) ["makerFeeRate"]=> float(0.0002) ["takerFeeRate"]=> float(0.0006) ["takerFixFee"]=> float(0) ["makerFixFee"]=> float(0) ["settlementFee"]=> NULL ["isDeleverage"]=> bool(true) ["isQuanto"]=> bool(true) ["isInverse"]=> bool(false) ["markMethod"]=> string(9) "FairPrice" ["fairMethod"]=> string(11) "FundingRate" ["fundingBaseSymbol"]=> string(9) ".DOTINT8H" ["fundingQuoteSymbol"]=> string(10) ".USDTINT8H" ["fundingRateSymbol"]=> string(14) ".DOTUSDTMFPI8H" ["indexSymbol"]=> string(9) ".KDOTUSDT" ["settlementSymbol"]=> string(0) "" ["status"]=> string(4) "Open" ["fundingFeeRate"]=> float(3.3E-5) ["predictedFundingFeeRate"]=> float(-6.6E-5) ["openInterest"]=> string(7) "2843669" ["turnoverOf24h"]=> float(28367591.293969) ["volumeOf24h"]=> float(3796103) ["markPrice"]=> float(7.655) ["indexPrice"]=> float(7.656) ["lastTradePrice"]=> float(7.654) ["nextFundingRateTime"]=> int(17666357) ["maxLeverage"]=> int(50) ["sourceExchanges"]=> array(5) { [0]=> string(5) "huobi" [1]=> string(4) "Okex" [2]=> string(7) "Binance" [3]=> string(6) "Kucoin" [4]=> string(7) "Bittrex" } ["premiumsSymbol1M"]=> string(11) ".DOTUSDTMPI" ["premiumsSymbol8H"]=> string(13) ".DOTUSDTMPI8H" ["fundingBaseSymbol1M"]=> string(7) ".DOTINT" ["fundingQuoteSymbol1M"]=> string(8) ".USDTINT" ["lowPrice"]=> float(6.713) ["highPrice"]=> float(7.934) ["priceChgPct"]=> float(0.1212) ["priceChg"]=> float(0.827) } [10]=> array(55) { ["symbol"]=> string(8) "FILUSDTM" ["rootSymbol"]=> string(4) "USDT" ["type"]=> string(6) "FFWCSX" ["firstOpenDate"]=> int(1614153600000) ["expireDate"]=> NULL ["settleDate"]=> NULL ["baseCurrency"]=> string(3) "FIL" ["quoteCurrency"]=> string(4) "USDT" ["settleCurrency"]=> string(4) "USDT" ["maxOrderQty"]=> int(1000000) ["maxPrice"]=> float(1000000) ["lotSize"]=> int(1) ["tickSize"]=> float(0.01) ["indexPriceTickSize"]=> float(0.01) ["multiplier"]=> float(0.1) ["initialMargin"]=> float(0.05) ["maintainMargin"]=> float(0.025) ["maxRiskLimit"]=> int(200000) ["minRiskLimit"]=> int(200000) ["riskStep"]=> int(100000) ["makerFeeRate"]=> float(0.0002) ......

**Comment by codewc** [comment]
The symbol of the BTC Contracts is `XBT`, so the parameter should be `XTBUSDTM`.

The symbol of the BTC Contracts will be uniformly modified from `XBT` to `BTC`. For example: USDT Margined Perpetual Contracts, the symbol will be changed from XBTUSDTM to BTCUSDTM.

**Comment by ISAAC-XXYYZZ** [comment]
Since this issue has already been addressed and there have been no updates for a long time, we will now close it.
If you need any further assistance, feel free to ask!
